### ISSUE TITLE
Return an array from Item.find if one was passed in

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/wikisnakker#8]
At the moment `Item.find` changes it's return value based on the number of arguments it's given. This makes it harder to write code that just uses the return value without knowing or caring what values were passed in. Ideally it would always return an array, then the person calling the method can just take the first value if that's what they need.

**Comment by tmtmtmtm** [comment]
I'm not so sure about the "Ideally" there. Asking for `.find('Q20530392')` and getting back an Array seems wrong to me.

**Comment by chrismytton** [comment]
So the code that triggered me to write this ticket was [this line in everypolitician-data](https://github.com/everypolitician/everypolitician-data/blob/ef7a04de60001f79826ee847f9c92875e07e6e78/lib/group_wikidata.rb#L22), I was passing it an array, which in some cases had only one element, but sometimes getting back a single `Item`.

Perhaps what I actually want is if I pass an array in I should get an array back, but if I pass a string in then I should just get a single item back.

**Comment by tmtmtmtm** [comment]
Ah, yes, collapsing a single item list and then assuming you were given a string is definitely bad. 

> Perhaps what I actually want is if I pass an array in I should get an array back, but if I pass a string in then I should just get a single item back.

Yep — that sounds good.
